/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SigninRouteImport } from './routes/signin'
import { Route as SplatRouteImport } from './routes/$'
import { Route as LayoutRouteRouteImport } from './routes/_layout/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiCharacterChatRouteImport } from './routes/api/character-chat'
import { Route as LayoutQuotasRouteImport } from './routes/_layout/quotas'
import { Route as LayoutPlaylistsRouteImport } from './routes/_layout/playlists'
import { Route as LayoutLibraryRouteImport } from './routes/_layout/library'
import { Route as LayoutLearnVideoIdRouteImport } from './routes/_layout/learn/$videoId'

const SigninRoute = SigninRouteImport.update({
  id: '/signin',
  path: '/signin',
  getParentRoute: () => rootRouteImport,
} as any)
const SplatRoute = SplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutRouteRoute = LayoutRouteRouteImport.update({
  id: '/_layout',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCharacterChatRoute = ApiCharacterChatRouteImport.update({
  id: '/api/character-chat',
  path: '/api/character-chat',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutQuotasRoute = LayoutQuotasRouteImport.update({
  id: '/quotas',
  path: '/quotas',
  getParentRoute: () => LayoutRouteRoute,
} as any)
const LayoutPlaylistsRoute = LayoutPlaylistsRouteImport.update({
  id: '/playlists',
  path: '/playlists',
  getParentRoute: () => LayoutRouteRoute,
} as any)
const LayoutLibraryRoute = LayoutLibraryRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => LayoutRouteRoute,
} as any)
const LayoutLearnVideoIdRoute = LayoutLearnVideoIdRouteImport.update({
  id: '/learn/$videoId',
  path: '/learn/$videoId',
  getParentRoute: () => LayoutRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/signin': typeof SigninRoute
  '/library': typeof LayoutLibraryRoute
  '/playlists': typeof LayoutPlaylistsRoute
  '/quotas': typeof LayoutQuotasRoute
  '/api/character-chat': typeof ApiCharacterChatRoute
  '/learn/$videoId': typeof LayoutLearnVideoIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/signin': typeof SigninRoute
  '/library': typeof LayoutLibraryRoute
  '/playlists': typeof LayoutPlaylistsRoute
  '/quotas': typeof LayoutQuotasRoute
  '/api/character-chat': typeof ApiCharacterChatRoute
  '/learn/$videoId': typeof LayoutLearnVideoIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_layout': typeof LayoutRouteRouteWithChildren
  '/$': typeof SplatRoute
  '/signin': typeof SigninRoute
  '/_layout/library': typeof LayoutLibraryRoute
  '/_layout/playlists': typeof LayoutPlaylistsRoute
  '/_layout/quotas': typeof LayoutQuotasRoute
  '/api/character-chat': typeof ApiCharacterChatRoute
  '/_layout/learn/$videoId': typeof LayoutLearnVideoIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$'
    | '/signin'
    | '/library'
    | '/playlists'
    | '/quotas'
    | '/api/character-chat'
    | '/learn/$videoId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$'
    | '/signin'
    | '/library'
    | '/playlists'
    | '/quotas'
    | '/api/character-chat'
    | '/learn/$videoId'
  id:
    | '__root__'
    | '/'
    | '/_layout'
    | '/$'
    | '/signin'
    | '/_layout/library'
    | '/_layout/playlists'
    | '/_layout/quotas'
    | '/api/character-chat'
    | '/_layout/learn/$videoId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LayoutRouteRoute: typeof LayoutRouteRouteWithChildren
  SplatRoute: typeof SplatRoute
  SigninRoute: typeof SigninRoute
  ApiCharacterChatRoute: typeof ApiCharacterChatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signin': {
      id: '/signin'
      path: '/signin'
      fullPath: '/signin'
      preLoaderRoute: typeof SigninRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$': {
      id: '/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof SplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout': {
      id: '/_layout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof LayoutRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/character-chat': {
      id: '/api/character-chat'
      path: '/api/character-chat'
      fullPath: '/api/character-chat'
      preLoaderRoute: typeof ApiCharacterChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout/quotas': {
      id: '/_layout/quotas'
      path: '/quotas'
      fullPath: '/quotas'
      preLoaderRoute: typeof LayoutQuotasRouteImport
      parentRoute: typeof LayoutRouteRoute
    }
    '/_layout/playlists': {
      id: '/_layout/playlists'
      path: '/playlists'
      fullPath: '/playlists'
      preLoaderRoute: typeof LayoutPlaylistsRouteImport
      parentRoute: typeof LayoutRouteRoute
    }
    '/_layout/library': {
      id: '/_layout/library'
      path: '/library'
      fullPath: '/library'
      preLoaderRoute: typeof LayoutLibraryRouteImport
      parentRoute: typeof LayoutRouteRoute
    }
    '/_layout/learn/$videoId': {
      id: '/_layout/learn/$videoId'
      path: '/learn/$videoId'
      fullPath: '/learn/$videoId'
      preLoaderRoute: typeof LayoutLearnVideoIdRouteImport
      parentRoute: typeof LayoutRouteRoute
    }
  }
}

interface LayoutRouteRouteChildren {
  LayoutLibraryRoute: typeof LayoutLibraryRoute
  LayoutPlaylistsRoute: typeof LayoutPlaylistsRoute
  LayoutQuotasRoute: typeof LayoutQuotasRoute
  LayoutLearnVideoIdRoute: typeof LayoutLearnVideoIdRoute
}

const LayoutRouteRouteChildren: LayoutRouteRouteChildren = {
  LayoutLibraryRoute: LayoutLibraryRoute,
  LayoutPlaylistsRoute: LayoutPlaylistsRoute,
  LayoutQuotasRoute: LayoutQuotasRoute,
  LayoutLearnVideoIdRoute: LayoutLearnVideoIdRoute,
}

const LayoutRouteRouteWithChildren = LayoutRouteRoute._addFileChildren(
  LayoutRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LayoutRouteRoute: LayoutRouteRouteWithChildren,
  SplatRoute: SplatRoute,
  SigninRoute: SigninRoute,
  ApiCharacterChatRoute: ApiCharacterChatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
